//this is adapted from catbook schema-many thanks to Kye for indicating we can use this! (https://piazza.com/class/kic6jaqsarc70r?cid=1049)

const mongoose = require("mongoose");

//define a comment schema for the database
const CommentSchema = new mongoose.Schema({
    creator_id: String,
    creator_name: String,
    parent: String, // links to the _id of a parent story (_id is an autogenerated field by Mongoose).
    contentTranslated: String,
    contentOriginal: String,
    submit_stamp: String,
    submit_stamp_raw: String
  });
  
  // compile model from schema
  module.exports = mongoose.model("comment", CommentSchema);  